use vanilla docker build

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -48,7 +48,7 @@ jobs:
             context: ./
             file: .docker/base/Dockerfile
             outputs: type=docker,dest=/tmp/warp.tar
-            tags: wanjohiryan/warp:latest
+            tags: warp:latest
 
         -
           name: Upload artifact
@@ -65,9 +65,6 @@ jobs:
       - 
         name: Checkout repo
         uses: actions/checkout@v3
-      - 
-          name: Setup Docker Buildx
-          uses: docker/setup-buildx-action@v2
       -
         name: Download artifact
         uses: actions/download-artifact@v2
@@ -81,14 +78,21 @@ jobs:
           docker image ls -a
       - 
         name: Build Docker example
-        uses: docker/build-push-action@v4
-        with:
-          context: ./
-          file: examples/brave/Dockerfile
-          push: false
-          build-args: WARP_IMAGE=wanjohiryan/warp:latest
-          load: true
-          tags: warp:brave
+        run: |
+          set -o pipefail
+          
+          cp examples/brave/Dockerfile .
+
+          output=$(docker build --tag warp:brave --build-arg WARP_IMAGE=warp:latest . 2>&1) || exitcode=$?
+
+          if [[ $exitcode != 0 ]]; then
+            echo "::error::Docker container failed with error: $exitcode"
+            echo "$output"
+            exit 1
+          else 
+            echo "Docker container ran successfully for 20 seconds."
+            exit 0
+          fi
       - 
         name: Run Docker Container example
         run: |
